settings:
    device: cpu

data:
    dataset_path: /Users/akshay/transformer/src/data/dataset/multi30k/
    vocab_path: /Users/akshay/transformer/src/data/dataset/vocab.pt
    max_padding: 72
    batch_size: 32

model:
    N: 6
    d_model: 512
    d_ff: 2048
    h: 8
    dropout: 0.1

algorithm:
    lr: 1.0
    warmup: 3000
    accum_iter: 10
    smoothing: 0.1
    epochs: 8