device: cpu

data:
    dataset_path: /Users/akshay/canvas/project/data/dataset/multi30k/
    vocab_path: /Users/akshay/canvas/project/data/dataset/vocab.pt
    max_padding: 72
    device: ${device}
    batch_size: 32

model:
    device: ${device}
    d_model: 512
    nhead: 8
    num_encoder_layers: 6
    num_decoder_layers: 6
    dim_feedforward: 2048
    dropout: 0.1

algorithm:
    lr: 1.0
    warmup: 3000
    accum_iter: 10
    smoothing: 0.1
    epochs: 8